num_species: 50
batch_size: 10
log_transform: True
job_name: test_experiment
save_path: svi_experiments
prior: log_uniform
lr: 0.01
edge_effect_ratio: .01
omega_min: 1.0e-2
omega_max: 1.0
gamma_min: 1.0e-62
gamma_max: 1.0
kappa: 10
num_flows: 2
hidden_dim: 8
num_epochs: 2000
patience: 500


